### ISSUE TITLE
Jumio.initNetverify not working on iOS once deployed in the appstore

### ISSUE THREAD

**Issue by jerviechronix** [Jumio/mobile-cordova#10]
Hi Jumio team, the Jumio.initNetverify function not working when I deployed the app in the appstore, but works perfectly when trying to build and run in xcode. When I debug the code the error message is "The Netverify SDK is not initialized yet. Call initNetverify() first."

cordova version: 11.0
ios version: 6.2.0

please help. thanks

**Comment by bratapfelmus** [comment]
Hello @jerviechronix, which version fo the SDK plugin are you using?

**Comment by jerviechronix** [comment]
Im using SDK version 3.9.2

**Comment by bratapfelmus** [comment]
If you are on Xcode 13 or above and the debug build works fine, but the SDK cannot be initialized in the release build, it most likely is due to a new option Apple has introduced to their distribution options --> https://github.com/Jumio/mobile-sdk-ios/blob/master/docs/known_issues.md#sdk-version-not-compatible-after-xcode-13-update

**Comment by jerviechronix** [comment]
It works like magic!!! Thank you @bratapfelmus :)
